# Generated by Django 3.1.6 on 2021-02-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_auto_20210214_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='tfno',
            field=models.CharField(max_length=10, verbose_name='Teléfono'),
        ),
    ]
